### ISSUE TITLE
Swagger endpoints blocked by new authentication

### ISSUE THREAD

**Issue by c1oneman** [phybros/servertap#46]
The new authentication (0.0.5) now blocks the /swagger and /swagger-doc endpoints. 
I have a running workaround on my branch that just adds to the check to see if the call is swagger.
But, the problem gets deeper when you make test calls through swagger, as the endpoints are still blocked due to no authentication key provided.

**Comment by phybros** [comment]
I thought you could add headers to Swagger UI. Maybe that's something we have to configure in code. Let me have a look real quick.

**Comment by phybros** [comment]
Yeah you have to tell Swagger that endpoints are protected or not, and then UI should present options around authentication to you. Have a look at here https://javalin.io/plugins/openapi and Ctrl-F for ".roles". I think that's what you need to annotate the methods with. You'll have to do a bit more digging to figure out the exact syntax in our code because we use annotations.

Good luck, let us know if you figure it out!

**Comment by c1oneman** [comment]
Would it be alright to just add
`@OpenApiParam(name = "key")`
to each endpoint?
